name: Bug report
description: Reporta un problema
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: desc
    attributes: { label: Descripción, placeholder: Qué pasó y qué esperabas }
    validations: { required: true }
  - type: textarea
    id: steps
    attributes: { label: Pasos, placeholder: "1. ... 2. ... 3. ..." }
  - type: input
    id: env
    attributes: { label: Entorno, placeholder: "web/android/ios/windows" }
  - type: textarea
    id: extra
    attributes: { label: Extra }
