name: Legacy Pages (disabled)

# This legacy workflow is intentionally disabled to avoid double deployments.
# Use .github/workflows/pages.yml for the active Pages workflow.
on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Legacy Pages workflow is disabled. Use pages.yml."
