name: E2E Full Suite

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # 03:00 UTC daily
  pull_request_target:
    types: [labeled]

jobs:
  run-full-e2e:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'schedule' ||
      (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'run-full-e2e'))
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Typecheck (relaxed)
        run: npm run typecheck:all
      - name: Build web app
        run: npm run build:all
      - name: Run full E2E suite
        run: npm run test:all --workspace apps/web
      - name: Upload test results (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/web/test-results
          if-no-files-found: ignore
