name: Flutter CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/flutter/**'
      - '.github/workflows/flutter-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'apps/flutter/**'
  workflow_dispatch:

jobs:
  analyze_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
      - name: Enable web
        run: flutter config --enable-web
      - name: Get deps
        working-directory: apps/flutter
        run: flutter pub get
      - name: Analyze
        working-directory: apps/flutter
        run: flutter analyze
      - name: Test
        working-directory: apps/flutter
        run: flutter test
